## Basic Configuration

baseurl = "https://vickyleigh.netlify.com"
builddrafts = false
canonifyurls = false
languageCode = "en-UK"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Vicky Leigh"
title = "Vicky Leigh"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
#googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Vicky Leigh"
intro = "R Stats & Local Gov Data"
description = ""
authorimage = "face.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Vicky Leigh's Blog"
keywords = "blog,data analysis,data science,R"

## Social Accounts
[params.social]
github = "vickyleigh"
twitter = "VickyLeigh_"
email = "vickyleigh795@gmail.com"

## Extras
[params.extra]
copyright = "© 2019"
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = true

## Main Menu
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
